"""Build fully populated rubric-aligned notebooks from auditable cells."""
import json
from pathlib import Path
R=Path(__file__).parent
def nb(cells):
 return {"cells":[{"cell_type":t,"metadata":{},"source":[s],**({"execution_count":None,"outputs":[]} if t=="code" else {})} for t,s in cells],"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.12"}},"nbformat":4,"nbformat_minor":5}

sol=[
("markdown","# FIT5196 Assessment 1 — Group030 Solution\nComplete structured parsing, transformation, reconciliation and validation evidence. **Members must add names and student IDs before submission.**"),
("markdown","## 0. Configuration and reproducibility\nAll paths are relative/configurable; the workflow performs no network I/O."),
("code","from pathlib import Path\nimport json, hashlib, xml.etree.ElementTree as ET\nimport pandas as pd\nGROUP_ID='Group030'; INPUT_DIR=Path('raw_input'); OUTPUT_DIR=Path('outputs'); TEMPLATE_DIR=Path('templates'); DICTIONARY_PATH=Path('public_data_dictionary.csv')\nOUTPUT_DIR.mkdir(exist_ok=True)\nfrom Group030_solution import build_tables, validate\nfrom Group030_text_functions import *\nprint({'group':GROUP_ID,'input':str(INPUT_DIR),'output':str(OUTPUT_DIR),'pandas':pd.__version__})"),
("markdown","### 0.1 Package integrity\nThe archive, manifest and source filenames must all identify Group030; hashes verify that the allocated inputs were not altered."),
("code","manifest=json.load(open('A1_manifest.json'))\nchecks=[]\nfor entry in manifest['files']:\n p=Path(entry['path']); checks.append({'path':entry['path'],'exists':p.exists(),'bytes':p.stat().st_size if p.exists() else None,'sha256_match':p.exists() and hashlib.sha256(p.read_bytes()).hexdigest()==entry['sha256']})\npd.DataFrame(checks)"),
("markdown","## 1. Parse and profile the two sources\nBoth documents are parsed with structured parsers. Regex is never used to reconstruct JSON/XML."),
("markdown","### 1.1 JSON structure and grain\n`customerProfiles` is one customer per element; `orders` is one order with nested header, repeated cart items and one delivery; `productReviews` is one review. Candidate keys are customerID, orderID, orderItemID, deliveryID and reviewID. JSON uses ISO dates/timestamps, Python booleans, numeric AUD values and empty strings for optional text."),
("code","with open(INPUT_DIR/f'{GROUP_ID}_commerce.json',encoding='utf-8') as f: js=json.load(f)\njson_profile=pd.DataFrame([{'collection':k,'python_type':type(v).__name__,'records':len(v) if isinstance(v,list) else 1,'top_fields':' | '.join(v[0].keys()) if isinstance(v,list) and v else ' | '.join(v.keys())} for k,v in js.items()])\njson_profile"),
("markdown","### 1.2 XML structure and grain\n`OperationsExport/Orders/Order` repeats orders; each contains Header, repeated Shopping_Cart/Item and one Delivery. ProductCatalogue/Product and ProductReviews/Review repeat at product and review grain. XML uses day-first dates, Y/N booleans, AUD labels, comma thousands separators, percentage strings and empty elements."),
("code","root=ET.parse(INPUT_DIR/f'{GROUP_ID}_operations.xml').getroot()\nxml_profile=pd.DataFrame([('Orders/Order','order',len(root.findall('./Orders/Order'))),('Shopping_Cart/Item','order item',len(root.findall('./Orders/Order/Shopping_Cart/Item'))),('Order/Delivery','delivery',len(root.findall('./Orders/Order/Delivery'))),('ProductCatalogue/Product','product',len(root.findall('./ProductCatalogue/Product'))),('ProductReviews/Review','review',len(root.findall('./ProductReviews/Review')))],columns=['path','grain','records'])\nxml_profile"),
("markdown","### 1.3 Source comparison, overlap and assumptions\nJSON uniquely supplies customers; XML uniquely supplies products. Orders, items, deliveries and reviews overlap partially across sources. Comparable fields are normalised first, then compared by primary key. Equal records collapse; any differing non-missing value is a validation conflict. No source-precedence rule is used. IDs retain case/leading zeros; missing prescribed strings become literal `NaN`."),
("code","tables,profile=build_tables(INPUT_DIR,DICTIONARY_PATH)\npd.DataFrame(profile['json'].items(),columns=['entity','JSON rows']).merge(pd.DataFrame(profile['xml'].items(),columns=['entity','XML rows']),on='entity',how='outer').fillna(0), profile['canonical']"),
("markdown","## 2. Source-to-target mapping\nAll 111 target fields retain template MAP IDs. Paths are structural, derivations specify formulas and all multi-source rows document comparison/conflict behaviour."),
("code","mapping=pd.read_csv('Group030_source_to_target_mapping.csv',keep_default_na=False)\ncore=['source_format','transformation_or_derivation','overlap_or_conflict_rule','notebook_evidence']\nsummary=mapping.groupby('output_table').agg(required_rows=('mapping_id','size'),core_complete=('mapping_id',lambda x:0))\nsummary['core_complete']=[mapping[mapping.output_table.eq(t)][core].ne('').all(axis=1).sum() for t in summary.index]\nsummary"),
("markdown","## 3. Text and regex functions\nProcessing order is: structured field retrieval → reference extraction → entity decode/NFC → tags → published markers/URLs/emoji → complete reference wrapper → promo wrapper → whitespace/lowercase → literal `NaN`. `review_body_clean` preserves multilingual letters; Latin analysis is derived separately."),
("code","cases=pd.read_csv(TEMPLATE_DIR/'A1_public_text_test_cases.csv',keep_default_na=False)\nresults=[]\nfor _,x in cases.iterrows():\n actual=str(globals()[x.function](x.input_value));results.append({'case_id':x.case_id,'function':x.function,'actual':actual,'expected':x.expected_output,'status':'PASS' if actual==x.expected_output else 'FAIL'})\npublic_results=pd.DataFrame(results);public_results"),
("code","student_tests=[('missing',clean_narrative_text(None),'NaN'),('Latin diacritic',build_latin_analysis('déjà 東京'),'déjà'),('non-Latin flag',contains_non_latin_script('déjà 東京'),True),('embedded order',extract_order_reference('XHORD123456'),'NaN'),('extended SKU',extract_product_sku('SKU-ABC_extra'),'NaN'),('extended promo',extract_promo_code('B3SAVE-24_more'),'NaN')]\npd.DataFrame(student_tests,columns=['case','actual','expected']).assign(status=lambda x:x.actual.eq(x.expected).map({True:'PASS',False:'FAIL'}))"),
("markdown","## 4. Build the six standardised relational tables\nThe maintained implementation is `Group030_solution.py`; the following cells expose each table's grain, field order, row flow and material derivations."),
("markdown","### 4.1 Orders\nOne canonical order per `order_id`. Timestamps, percentages, booleans, coordinates and narrative are normalised. `order_price` is recomputed from rounded canonical lines; GST is included `order_price/11`; total applies discount then delivery."),
("code","tables['orders'].head(3), {'rows':len(tables['orders']),'unique_keys':tables['orders'].order_id.nunique(),'columns':tables['orders'].columns.tolist()}"),
("markdown","### 4.2 Order items\nOne row per `order_item_id`; nested arrays are flattened without joining reviews. `line_revenue = round(quantity × unit_price, 2)`."),
("code","tables['order_items'].head(3),tables['order_items'].agg({'quantity':['min','max'],'unit_price':['min','max'],'line_revenue':['min','max']})"),
("markdown","### 4.3 Customers\nOne row per JSON customer. Postcodes remain strings so leading zeros would survive; consent is boolean and signup date is ISO."),
("code","tables['customers'].head(3),tables['customers'][['loyalty_tier','customer_segment','preferred_language']].describe()"),
("markdown","### 4.4 Deliveries\nOne completed delivery per `delivery_id`; XML/JSON dates and boolean alternatives are reconciled. Narrative is cleaned through the same bounded function."),
("code","tables['deliveries'].head(3),tables['deliveries'].groupby(['carrier','service_level']).size().rename('rows')"),
("markdown","### 4.5 Products\nOne XML catalogue row per product. AUD cost/price, dates, flags and product description are standardised."),
("code","tables['products'].head(3),tables['products'].groupby('category').agg(products=('product_id','size'),mean_price=('unit_price','mean'))"),
("markdown","### 4.6 Product reviews\nOne canonical review per `review_id`; structured attributes are reconciled and raw text yields multilingual clean text, Latin analysis, references, flags and measures."),
("code","tables['product_reviews'].head(3),tables['product_reviews'].groupby(['language_code','contains_non_latin_script']).size().sort_values(ascending=False).head(12)"),
("markdown","## 5. Reconciliation and relationships\nRaw-to-canonical counts demonstrate partial overlap. Reconciliation is key-driven and deterministic; zero conflicts means overlapping values agreed after normalisation."),
("code","flow=[]\nfor table,rawname in [('orders','orders'),('order_items','order_items'),('deliveries','deliveries'),('product_reviews','reviews')]:\n raw=profile['json'][rawname]+profile['xml'][rawname];flow.append({'table':table,'JSON':profile['json'][rawname],'XML':profile['xml'][rawname],'raw_total':raw,'canonical':len(tables[table]),'overlap_removed':raw-len(tables[table])})\npd.DataFrame(flow),{'normalised_conflicts':len(profile['conflicts'])}"),
("markdown","## 6. Validation register\nEach executable check reports a stable ID, observed result, PASS/FAIL and resolution. Coverage includes schema/order, missing representation, PK/FK, row flow, conflict detection, arithmetic, ranges, temporal order, references and multilingual behaviour."),
("code","dictionary=pd.read_csv(DICTIONARY_PATH);validation_register=validate(tables,dictionary,profile)\nvalidation_register"),
("code","validation_register.groupby('status').size(), validation_register[validation_register.status.ne('PASS')]"),
("markdown","## 7. Deterministic export\nOnly dictionary fields, in published order, enter the six submitted CSVs. Reading with `keep_default_na=False` confirms literal `NaN` is retained."),
("code","for name,df in tables.items():df.to_csv(OUTPUT_DIR/f'{GROUP_ID}_{name}_standardised.csv',index=False,na_rep='NaN')\nvalidation_register.to_csv(OUTPUT_DIR/f'{GROUP_ID}_validation_register.csv',index=False)\nroundtrip={n:list(pd.read_csv(OUTPUT_DIR/f'{GROUP_ID}_{n}_standardised.csv',keep_default_na=False).columns)==list(tables[n].columns) for n in tables}\nroundtrip"),
("markdown","## 8. Final reproducibility record\nFresh offline execution recreates six CSVs and all validation evidence without manual edits, certified counts, live services or absolute paths."),
("code","assert public_results.status.eq('PASS').all();assert validation_register.status.eq('PASS').all();assert all(roundtrip.values());print('FINAL STATUS: PASS — public tests, validation register and round-trip schemas')")]

eda=[
("markdown","# FIT5196 Assessment 1 — Group030 EDA\nFocused analysis recreated only from the six submitted CSVs. **Members must add names and student IDs.**"),
("markdown","## 0. Configuration and data loading"),("code","from pathlib import Path\nimport pandas as pd\nGROUP_ID='Group030';OUTPUT_DIR=Path('outputs')\nfrom Group030_EDA import load_tables,make_eda\ntables=load_tables();pd.DataFrame({'table':tables.keys(),'rows':[len(x) for x in tables.values()],'columns':[len(x.columns) for x in tables.values()]})"),
("markdown","## 1. Context and data-preparation assurance\nThe 2018 retailer export covers six relational grains. Structured parsing, normalisation-before-reconciliation, published GST/discount arithmetic and separate multilingual/Latin text are documented in MAP-*. VAL-SCHEMA/MISS-*, VAL-PK/FK-*, VAL-FLOW-*, VAL-ARITH/RANGE-*, VAL-TIME-* and VAL-TEXT-* all pass. Every EDA join declares cardinality and asserts unchanged left-grain counts."),
("code","figures,metrics=make_eda()"),
("markdown","## 2. Seven assessed visualisations"),
("markdown","### Figure 1 — What constitutes a typical versus high-value order?\n**Unit/denominator:** order; all 5,000 canonical orders. **Table:** orders; no join. **Metric:** net order_total distribution and empirical thresholds. **Interpretation:** median $2,555.44; top decile starts at $5,760.76. **Limitation:** high totals may reflect product mix and are not profit."),("code","figures[0]"),
("markdown","### Figure 2 — Do deeper coupons correspond to larger gross baskets?\n**Unit/denominator:** order within each discount group (n shown in metric table). **Table:** orders. **Metric:** group means with 95% normal-approximation CIs. **Interpretation:** gross means are broadly flat while realised totals fall with depth. **Limitation:** coupon assignment is observational, so the plot does not estimate incremental lift."),("code","pd.DataFrame(metrics['discount']).round(2); figures[1]"),
("markdown","### Figure 3 — Which categories contribute estimated gross margin?\n**Unit/denominator:** all 15,723 order-item lines. **Join:** order_items.product_id → products.product_id, many-to-one; row count asserted unchanged. **Metric:** Σ(line revenue − quantity×catalogue unit cost). **Interpretation:** Home Entertainment leads. **Limitation:** discounts, returns and overhead are not allocated, so this is not accounting profit."),("code","pd.DataFrame(metrics['category']).round(2); figures[2]"),
("markdown","### Figure 4 — Are monthly changes driven by volume or order value?\n**Unit/denominator:** month, based on all orders; panels avoid misleading dual axes. **Table:** orders. **Metrics:** count and mean net total. **Interpretation:** volume and AOV vary moderately with no persistent monotonic pattern. **Limitation:** one year and unequal month length prevent a seasonality claim."),("code","pd.DataFrame(metrics['monthly']).round(2); figures[3]"),
("markdown","### Figure 5 — Does historical frequency carry into the current period?\n**Unit/denominator:** 500 customers. **Join:** customer-level order aggregation → customers.customer_id, one-to-one; all customers retained. **Metric:** prior 12-month versus current count; Pearson r=0.08. **Interpretation:** history alone is weak. **Limitation:** correlation is linear and ignores tenure/campaign exposure."),("code","{'pearson_r':metrics['history_corr']};figures[4]"),
("markdown","### Figure 6 — Which carrier/service cells warrant operational review?\n**Unit/denominator:** completed delivery within each carrier×service cell. **Join:** deliveries.order_id → orders.order_id, one-to-one. **Metric:** OTIF rate with 95% Wilson CI. **Interpretation:** cells differ, but overlapping intervals caution against simple ranking. **Limitation:** route/customer mix is uncontrolled."),("code","pd.DataFrame(metrics['otif_cells']).round(4);figures[5]"),
("markdown","### Figure 7 — Is OTIF associated with review rating?\n**Unit/denominator:** 7,000 reviews. **Join:** reviews.order_id → deliveries.order_id, many-to-one; review row count asserted unchanged. **Metric:** mean rating and 95% CI. **Interpretation:** difference is only about 0.02 points. **Limitation:** reviewers are selected and product experience can confound the association."),("code","pd.DataFrame(metrics['rating_otif']).round(4);figures[6]"),
("markdown","## 3. Exactly ten evidence-based findings\n1. Across 5,000 orders, median net total was $2,555.44 and the top decile began at $5,760.76 (Figure 1). The upper tail makes a mean unrepresentative; category mix may explain it, so investigate rather than automatically target.\n\n2. Gross basket means stayed roughly $3,195–$3,359 across discount groups, while realised totals fell from $3,209 at 0% to $2,533 at 25% (n=156; Figure 2). Assignment is non-random; test causal lift before increasing discounts.\n\n3. Home Entertainment contributed about $1.04m estimated gross margin across 1,190 lines (Figure 3). Catalogue cost omits overhead, returns and discounts; add realised costs before assortment action.\n\n4. Monthly volume ranged 364–438 and AOV about $2,884–$3,115 (Figure 4). One year cannot identify recurring seasonality; acquire multi-year and campaign data.\n\n5. Prior/current frequency correlation was r=0.08 across 500 customers (Figure 5). History alone has weak ranking value; validate richer predictors temporally.\n\n6. OTIF was 89.3% across 5,000 deliveries (Figure 6), leaving meaningful improvement scope; use carrier/service strata rather than the aggregate.\n\n7. DHL Express was lowest at 87.0% OTIF (n=216; Figure 6), but intervals overlap peers. Control route mix and gather repeated periods before supplier action.\n\n8. OTIF versus non-OTIF mean rating differed by only about 0.02 points across 7,000 reviews (Figure 7). Selection/confounding can mask effects; examine low-rating risk and delay severity.\n\n9. Figure 3 retained all 15,723 item rows after the many-to-one product join, so margin was not inflated. It remains pre-discount because line discount allocation is absent.\n\n10. Text assurance found 303/7,000 reviews with non-Latin letters. Erasure would discard customer evidence; preserve multilingual text and audit language-level model performance."),
("markdown","## 4. Exactly five future ML questions\n### MLQ-1 — OTIF-risk classification\nDecision/unit/target: proactive intervention per order / OTIF failure. Decision-time predictors: warehouse, carrier, service, distance, expedited flag, basket and timing. Rolling temporal split; PR-AUC, calibration and recall at capacity. Exclude delivered date, delay reason and tracking outcomes; audit geographic/service false negatives.\n\n### MLQ-2 — Weekly demand forecasting\nStaffing per channel-week / order count. Use lagged counts, calendar and known campaigns; rolling-origin validation, WAPE and interval coverage. One year limits seasonality; promotions must be known at forecast time.\n\n### MLQ-3 — Low-rating classification\nService recovery per completed order / 1–2-star review. Use product, customer history and delivery facts available before outreach; temporal split, PR-AUC and calibration. Text/helpful votes leak; reviewer selection and language fairness matter.\n\n### MLQ-4 — Customer-frequency regression\nRetention capacity per customer / next-90-day count. Use past history, tier, acquisition and past mix; cohort temporal split, MAE and Poisson deviance. Exclude future orders and updated lifetime value; audit protected proxies.\n\n### MLQ-5 — Product clustering\nAssortment roles per product / stable demand-value profiles using lagged volume, revenue, margin, rating and price. Test time stability, silhouette and merchant interpretability. Scaling and sparse exposure may dominate."),
("markdown","## 5. Limitations and conclusion\nThis is one observational retailer-year with repeated entities. Coupon/delivery assignment is non-random; reviews condition on reviewers; catalogue cost is not realised cost; dates are coarse and subgroup sizes differ. The clearest signals are category concentration and heterogeneous OTIF. Coupon lift needs experimental evidence; historical frequency is weak alone; rating averages barely differ by OTIF. Future work requires temporal validation, leakage control and subgroup monitoring.")]

(R/'Group030_solution.ipynb').write_text(json.dumps(nb(sol),ensure_ascii=False,indent=1),encoding='utf-8')
(R/'Group030_EDA.ipynb').write_text(json.dumps(nb(eda),ensure_ascii=False,indent=1),encoding='utf-8')
